package utilities;

import java.util.Dictionary;
import java.util.List;
import java.util.Map;

import org.apache.commons.collections4.map.HashedMap;

public class Constants {
    public static  int WEBDRIVER_TIMEOUT = 60;
    public static  String BROWSER = "chrome";
    public static  String getTimeType = "AvailableTimeType()?$format=json&$expand=timeTypeNav&$select=timeTypeNav/externalName_en_US&$inlinecount=allpages";
    public static String employeeID = "";
    public static String timeType = "";
    public static String restURL = "";
    public static String startDate = "";
    public static String effDate = "";
    public static String endDate = "";
    public static String ExtendtimeType = "";
    public static String serviceAwardDate = "";
    public static String randomTermDate = "";
    public static String randomTermRsn = "";
    public static String TermRsnType = "";
    public static String Terminator = "";
    public static String Approvers = "";
    public static String TermRsnMsg = "";
    public static String PositionApprover1 = "";
    public static String PositionApprover2 = "";
    public static String PositionNumber = "";
    public static String PositionType = "";
    public static String JobTitle = "";
    public static String HireDate = "";
    public static String CostCenter = "";
    public static String CompanyCode = "";
    public static String Position = "";
    public static String UserName = "";
    public static String DateOfBirth = "";
    public static String Gender = "";
    public static String MaritalStatus = "";
    public static boolean nodata = true;
    public static String paycomponent = "";
    public static String amount = "";
    public static int count = 1;
    public static int btncount = 1;
    public static String wob = "";
    public static String room = "";
    public static String building = "";
    public static String careerstage = "";
    public static String level = "";
    public static String levelStructure = "";
    public static String incentiveplan = "";
    public static String firstname = "";
    public static String lastname = "";
    public static String managerID = "";
    public static String City = "";
    public static String Country = "";
    public static String County = "";
    public static String State = "";
    public static String Zipcode = "";
    public static String AddressLine1 = "";
    public static String AddressLine2 = "";
    public static String UpdateType = "";
    public static String EmploymentType = "";
    public static String WorkforceClass = "";
    public static String CurrentProxyUser = "";
    public static String EventReason = "";
    public static String ICIMSActionType = "";
    public static String lastKnownEmpID = "";
    public static String profession = "";
    public static String discipline = "";
    public static String disciplinestructure = "";
    public static String incentiveplanStructure = "";
    public static String qualifier1Structure = "";
    public static String qualifier2Structure = "";
    public static String standardTitleStructure = "";
    public static String qualifier1 = "";
    public static String qualifier2 = "";
    public static String structure = "";
    public static String geozone = "";
    public static String payScale = "";
    public static String payScaleArea = "";
    public static String channelOrg = "";
    public static String parentProfession = "";
    public static String managerUserName = "";
    public static String UserEmailID = "";
    public static String NATIONALID = "";
    public static String NATIONALIDTEXT = "";
    public static String probationEndDate = "";
    public static String ReportsToname = "";
    public static String ReportsToemail = "";
    public static String Reporteename = "";
    public static String Reporteeemail = "";
    public static String RequestNumber = "";
    public static String terminationType = "";
    public static String Status = "";
    public static String EmailAlias = "";
    public static String HWPRequisionNo = "";
    public static boolean flag = false;
    public static List<String> approversList;
    public static List<String> positionNumberList;
    public static Map <String,String> dictionary = new HashedMap();
    public static Map<String, String> Positiondictionary = new HashedMap();
	public static String Sheetname;
    public void init()
    {
        employeeID = "";
        timeType = "";
        restURL = "";
        startDate = "";
        effDate = "";
        endDate = "";
        ExtendtimeType = "";
        serviceAwardDate = "";
        randomTermDate = "";
        randomTermRsn = "";
        TermRsnType = "";
        Terminator = "";
        Approvers = "";
        TermRsnMsg = "";
        PositionApprover1 = "";
        PositionApprover2 = "";
        PositionNumber = "";
        PositionType = "";
        JobTitle = "";
        HireDate = "";
        CostCenter = "";
        CompanyCode = "";
        Position = "";
        UserName = "";
        DateOfBirth = "";
        Gender = "";
        MaritalStatus = "";
        nodata = true;
        paycomponent = "";
        amount = "";
        count = 1;
        btncount = 1;
        wob = "";
        room = "";
        building = "";
        careerstage = "";
        level = "";
        levelStructure = "";
        incentiveplan = "";
        firstname = "";
        lastname = "";
        managerID = "";
        City = "";
        Country = "";
        County = "";
        State = "";
        Zipcode = "";
        AddressLine1 = "";
        AddressLine2 = "";
        UpdateType = "";
        EmploymentType = "";
        WorkforceClass = "";
        CurrentProxyUser = "";
        EventReason = "";
        ICIMSActionType = "";
        lastKnownEmpID = "";
        profession = "";
        discipline = "";
        disciplinestructure = "";
        incentiveplanStructure = "";
        qualifier1Structure = "";
        qualifier2Structure = "";
        standardTitleStructure = "";
        qualifier1 = "";
        qualifier2 = "";
        structure = "";
        geozone = "";
        payScale = "";
        payScaleArea = "";
        channelOrg = "";
        parentProfession = "";
        managerUserName = "";
        UserEmailID = "";
        flag = false;
        NATIONALID = "";
        NATIONALIDTEXT = "";
        ReportsToname = "";
        ReportsToemail = "";
        Reporteename = "";
        Reporteeemail = "";
        RequestNumber = "";
        terminationType = "";
        Sheetname="";
        dictionary.clear();
    }
}
	


